[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cluster-snek"
version = "0.1.1"
description = "Professional-grade Kubernetes GitOps automation with comprehensive deployment modes"
requires-python = ">=3.12"
<<<<<<< HEAD
dependencies = ["PyYAML", "GitPython"]

[project.optional-dependencies]
test = ["pytest"]
=======
authors = [
    {name = "Tyler Zervas", email = "tzervas@users.noreply.github.com"}
]
license = {text = "MIT"}
readme = "README.md"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.12",
    "Topic :: System :: Systems Administration",
    "Topic :: System :: Installation/Setup",
    "Topic :: System :: Systems Administration",
    "Typing :: Typed",
]
dependencies = [
    "PyYAML>=6.0.1",
    "kubernetes>=28.1.0",
    "typer>=0.9.0",
    "rich>=13.6.0",
    "python-gnupg>=0.5.1",
    "requests>=2.31.0",
    "pathspec>=0.11.2",
    "click>=8.1.7",
    "pydantic>=2.5.2",
    "jinja2>=3.1.2"
]

[project.optional-dependencies]
test = [
    "pytest>=7.4.3",
    "pytest-cov>=4.1.0",
    "pytest-asyncio>=0.21.1",
    "pytest-mock>=3.12.0",
    "coverage>=7.3.2",
    "responses>=0.24.1"
]
dev = [
    "black>=23.11.0",
    "isort>=5.12.0",
    "flake8>=6.1.0",
    "mypy>=1.7.0",
    "pre-commit>=3.5.0",
    "pylint>=3.0.2",
    "types-PyYAML>=6.0.12.12",
    "types-requests>=2.31.0.10",
    "ruff>=0.1.6"
]
>>>>>>> 64a936c (feat: restructure project layout and add base implementation)

[project.urls]
Homepage = "https://github.com/tzervas/cluster_snek"
Repository = "https://github.com/tzervas/cluster_snek.git"
Issues = "https://github.com/tzervas/cluster_snek/issues"

[project.scripts]
cluster-snek = "cluster_snek.cli.main:main"

[tool.setuptools]
packages = ["cluster_snek"]

[tool.black]
line-length = 88
target-version = ['py312']
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
addopts = "-v --cov=cluster_snek --cov-report=xml --cov-report=term-missing"

[tool.coverage.run]
source = ["cluster_snek"]
omit = ["tests/*", "**/__init__.py"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if TYPE_CHECKING:",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
    "pass",
    "raise ImportError"
]

[tool.ruff]
line-length = 88
target-version = "py312"
select = ["E", "F", "B", "I", "UP", "C", "W", "N"]
