[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cluster-snek"
version = "0.1.1"
description = "Professional-grade Kubernetes GitOps automation with comprehensive deployment modes"
requires-python = ">=3.12"
<<<<<<< HEAD
dependencies = [
    "PyYAML>=6.0.1",
    "kubernetes>=28.1.0",
    "typer>=0.9.0",
    "rich>=13.6.0"
]
=======
dependencies = ["PyYAML", "GitPython"]
>>>>>>> 2bd2747 (Convergence (#3))

[project.optional-dependencies]
test = [
    "pytest>=7.4.3",
    "pytest-cov>=4.1.0",
    "pytest-asyncio>=0.21.1"
]
dev = [
    "black>=23.11.0",
    "flake8>=6.1.0",
    "mypy>=1.7.0",
    "pre-commit>=3.5.0",
    "pylint>=3.0.2",
    "types-PyYAML>=6.0.12.12"
]

[project.scripts]
cluster-snek = "cluster_snek.cluster_snek:main"
